//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lagoo.BusinessLogic.Resources.CommandsAndQueries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lagoo.BusinessLogic.Resources.CommandsAndQueries.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token is not provided.
        /// </summary>
        public static string AccessTokenIsEmpty {
            get {
                return ResourceManager.GetString("AccessTokenIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with the given email was not found.
        /// </summary>
        public static string AccountWasNotFoundByEmail {
            get {
                return ResourceManager.GetString("AccountWasNotFoundByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with the data received from external authentication service was not found.
        /// </summary>
        public static string AccountWasNotFoundByExternalAuthServiceData {
            get {
                return ResourceManager.GetString("AccountWasNotFoundByExternalAuthServiceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password does not match password.
        /// </summary>
        public static string ConfirmPasswordDoesNotMatchPassword {
            get {
                return ResourceManager.GetString("ConfirmPasswordDoesNotMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID is not provided.
        /// </summary>
        public static string DeviceIdIsNotProvided {
            get {
                return ResourceManager.GetString("DeviceIdIsNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty.
        /// </summary>
        public static string EmailIsEmpty {
            get {
                return ResourceManager.GetString("EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email.
        /// </summary>
        public static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be longer than {0} characters.
        /// </summary>
        public static string EmailIsTooLong {
            get {
                return ResourceManager.GetString("EmailIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External authentication service type has to be specified.
        /// </summary>
        public static string ExternalAuthServiceNotSpecified {
            get {
                return ResourceManager.GetString("ExternalAuthServiceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be empty.
        /// </summary>
        public static string FirstNameIsEmpty {
            get {
                return ResourceManager.GetString("FirstNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be longer than {0} characters.
        /// </summary>
        public static string FirstNameIsTooLong {
            get {
                return ResourceManager.GetString("FirstNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid data for creating an account.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid external authentication service.
        /// </summary>
        public static string InvalidExternalAuthService {
            get {
                return ResourceManager.GetString("InvalidExternalAuthService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JWT claims.
        /// </summary>
        public static string InvalidJwtClaims {
            get {
                return ResourceManager.GetString("InvalidJwtClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given password is not valid.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot be empty.
        /// </summary>
        public static string LastNameIsEmpty {
            get {
                return ResourceManager.GetString("LastNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot be longer than {0} characters.
        /// </summary>
        public static string LastNameIsTooLong {
            get {
                return ResourceManager.GetString("LastNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to be at least {0} characters long.
        /// </summary>
        public static string PasswordIsTooShort {
            get {
                return ResourceManager.GetString("PasswordIsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to contain at least on lowercase latter.
        /// </summary>
        public static string PasswordWithoutLowercaseLetters {
            get {
                return ResourceManager.GetString("PasswordWithoutLowercaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to contain at least on numeric character.
        /// </summary>
        public static string PasswordWithoutNumericCharacters {
            get {
                return ResourceManager.GetString("PasswordWithoutNumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to contain at least one special character.
        /// </summary>
        public static string PasswordWithoutSpecialCharacters {
            get {
                return ResourceManager.GetString("PasswordWithoutSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to contain at least one uppercase letter.
        /// </summary>
        public static string PasswordWithoutUppercaseLetters {
            get {
                return ResourceManager.GetString("PasswordWithoutUppercaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token value is not provided.
        /// </summary>
        public static string RefreshTokenValueIsEmpty {
            get {
                return ResourceManager.GetString("RefreshTokenValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token with specified value was not found.
        /// </summary>
        public static string RefreshTokenWasNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token was not found or expired.
        /// </summary>
        public static string RefreshTokenWasNotFoundOrExpired {
            get {
                return ResourceManager.GetString("RefreshTokenWasNotFoundOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have external logins.
        /// </summary>
        public static string UserDoesNotHaveExternalLogins {
            get {
                return ResourceManager.GetString("UserDoesNotHaveExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have external login from the specified external authentication service.
        /// </summary>
        public static string UserDoesNotHaveSpecificExternalLogin {
            get {
                return ResourceManager.GetString("UserDoesNotHaveSpecificExternalLogin", resourceCulture);
            }
        }
    }
}
