namespace Lagoo.Api.Common.Extensions;

/// <summary>
///  Auto generated API extension methods for <see cref="IServiceCollection"/>
/// </summary>
public static class AutoGeneratedApiServiceCollectionExtensions
{
    public static void AddAutoGeneratedApi(this IServiceCollection services)
    {
        services.AddOpenApiDocument(settings => settings.Title = "Lagoo API");
    }
}