namespace Lagoo.Api.Common.Extensions;

public static class CustomServiceCollectionExtensions
{
    public static void AddAutoGeneratedApi(this IServiceCollection services)
    {
        services.AddOpenApiDocument(settings => settings.Title = "Lagoo API");
    }

    public static void AddConfiguredCors(this IServiceCollection services)
    {
        services.AddCors(options =>
        {
            options.AddPolicy("EnableCORS", builder =>
            {
                builder
                    .AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .WithExposedHeaders("Content-Disposition");
            });
        });
    }
}